version: '3'

volumes:
  src:

services:
  q2a:
    build: ./q2a
    restart: always
    volumes:
      - "src:/var/www/html/"
      - "./conf/qa-config.php:/var/www/html/qa-config.php:ro"

  web:
    image: nginx:latest
    restart: always
    ports:
     - "80:80"
    depends_on:
     - q2a
    volumes:
      - "./conf/nginx.conf:/etc/nginx/nginx.conf:ro"
      - "src:/var/www/html/"
